name: sgrunoff
channels:
  - conda-forge
dependencies:
  - python=3.10
  - setuptools
  - pip
  - numpy
  - scipy
  - matplotlib
  - gdal
  - rasterio
  - fiona
  - seaborn
  - richdem
  - pyyaml
  - pylint
  - cartopy
  - geopandas
  - xarray
  - pip:
      - pysheds
      - matplotlib-scalebar
